# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1536"
    vb.cpus = 2
  end

  config.vm.define "centos" do |c|
    c.vm.hostname = "test-online-centos"
    c.vm.box = "generic/centos7"
    c.vm.network "private_network", ip: "10.240.0.70"
    c.vm.network "forwarded_port", guest: 22, host: 2370, id: "ssh"
  end

  config.vm.define "ubuntu" do |c|
    c.vm.hostname = "test-online-ubuntu"
    c.vm.box = "generic/ubuntu1804"
    c.vm.network "private_network", ip: "10.240.0.71"
    c.vm.network "forwarded_port", guest: 22, host: 2371, id: "ssh"    
  end
end
