# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
  config.ssh.insert_key = false

  #config.vm.synced_folder ".", "/home/vagrant/kubeadm-offline", owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "4096"
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #  sudo swapoff -a
  #SHELL
end
