# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/focal64"
  config.vm.box = "generic/ubuntu2004"

  # config.vm.box_check_update = false
  config.vm.hostname = "ubuntu"
  config.vm.network "private_network", ip: "192.168.56.61"
  config.vm.network "forwarded_port", guest: 22, host: 2361, id: "ssh"
  config.ssh.insert_key = false

  #config.vm.synced_folder "../..", "/home/vagrant/k8s-installer", owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2048"
  end
end
