# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.ssh.insert_key = false

  config.vm.define "master-0" do |c|
    c.vm.hostname = "master-0"
    c.vm.network "private_network", ip: "10.240.0.10"
    c.vm.network "forwarded_port", guest: 22, host: 2310, id: "ssh"
    c.vm.provider "virtualbox" do |vb|
      vb.memory = "1532"
      vb.cpus = 2
    end
  end

  (0..2).each do |n|
    config.vm.define "worker-#{n}" do |c|
      c.vm.hostname = "worker-#{n}"
      c.vm.network "private_network", ip: "10.240.0.2#{n}"
      c.vm.network "forwarded_port", guest: 22, host: 2320 + n, id: "ssh"
      c.vm.provider "virtualbox" do |vb|
        vb.memory = "2560"
        vb.cpus = 2

        # attach virtual disk
        vdisk = "vdisks/sd-worker-#{n}.vdi"
        unless File.exist?(vdisk)
          vb.customize [
                           'storagectl', :id,
                           '--name', 'SATA Controller',
                           '--add', 'sata',
                           '--controller', 'IntelAHCI']
          vb.customize [
                           'createmedium', 'disk',
                           '--filename', vdisk,
                           '--format', 'VDI',
                           '--size', 10 * 1024 ]
        end
        vb.customize [
                         'storageattach', :id,
                         '--storagectl', 'SATA Controller',
                         '--port', 1,
                         '--device', 0,
                         '--type', 'hdd',
                         '--medium', vdisk]
      end
    end
  end
end
