# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "generic/centos7"
  config.vm.box = "bento/almalinux-8"
  config.ssh.insert_key = false

  config.vm.define "master-0" do |c|
    c.vm.hostname = "master-0"
    c.vm.network "private_network", ip: "192.168.56.10"
    c.vm.network "forwarded_port", guest: 22, host: 2310, id: "ssh"
    c.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  (0..2).each do |n|
    config.vm.define "worker-#{n}" do |c|
      c.vm.hostname = "worker-#{n}"
      c.vm.network "private_network", ip: "192.168.56.2#{n}"
      c.vm.network "forwarded_port", guest: 22, host: 2320 + n, id: "ssh"
      c.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end
end
