# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1536"
    vb.cpus = 2
  end

  config.vm.define "centos" do |c|
    c.vm.hostname = "centos"
    c.vm.network "private_network", ip: "10.240.0.50"
    c.vm.box = "generic/centos7"
  end

  config.vm.define "ubuntu" do |c|
    c.vm.hostname = "ubuntu"
    c.vm.network "private_network", ip: "10.240.0.51"
    c.vm.box = "generic/ubuntu1804"
  end
end
