- name: Uninstall docker.io / containerd if present
  package:
    name:
      - docker.io
      - docker-io
      - containerd
    state: absent

- name: Download and install runc (online)
  get_url:
    url: "{{ runc_download_url }}"
    dest: /usr/local/bin/runc
    mode: 0755
  environment: "{{ proxy_env }}"
  when: not offline_install

- name: Install runc (offline)
  copy:
    src: ./offline-files/{{ runc_file }}
    dest: /usr/local/bin/runc
    mode: 0755
  when: offline_install

- name: Install containerd (online)
  unarchive:
    src: "{{ containerd_download_url }}"
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
    remote_src: yes
  when: not offline_install

- name: Install containerd (offline)
  unarchive:
    src: ./offline-files/{{ containerd_tarball }}
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
  when: offline_install

- name: Create /etc/containerd dir
  file:
    path: /etc/containerd
    state: directory

- name: Install containerd config.toml
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Install containerd unit file
  copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service

- name: Enable containerd service
  systemd:
    name: containerd
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Install crictl.yaml
  copy:
    src: crictl.yaml
    dest: /etc

- include_tasks: nerdctl.yml
